export enum NationalityConverter {
    'AU' = 'Australia',
    'BR' = 'Brazil',
    'CA' = 'Canada',
    'CH' = 'Czech Republic',
    'DE' = 'Germany',
    'DK' = 'Denmark',
    'ES' = 'Spain',
    'FI' = 'Finland',
    'FR' = 'France',
    'GB' = 'United Kingdom',
    'IE' = 'Ireland',
    'IN' = 'India',
    'IR' = 'Iran',
    'MX' = 'Mexico',
    'NL' = 'Netherlands',
    'NO' = 'Norway',
    'NZ' = 'New Zealand',
    'RS' = 'Serbia',
    'TR' = 'Turkey',
    'UA' = 'Ukraine',
    'US' = 'United States'
  }